Yoctol/uttut

.editorconfig
.travis.yml
Makefile

Dev with Makfile

---

Makefile
requirements_dev.txt
uttut/elements.c
uttut/elements.pyx
uttut/tests/test_elements.py

The end position is now in parallel with python and javascript convention

Fix to_dict of elements

---

requirements_dev.txt
uttut/annotated_sentence_transformer.py

Wait until https://github.com/Yoctol/flake8-config-yoctol/pull/2 on pip.

yoctol flake8 0.0.11

---

.flake8
uttut/__init__.py
uttut/transformers/__init__.py
uttut/transformers/base.py
uttut/transformers/ordinal_label.py
uttut/transformers/tests/test_ordinal_label.py

pick from #26 .  Add data transformer

add data transformer structure

---

uttut/pipeline/bian/group.py
uttut/pipeline/bian/tests/test_group.py

需要思考的東西:
要不要讓使用者碰到Edit, Span 
還是只讓使用者直接使用EditGroup, SpanGroup

little modification

---

uttut/pipeline/bian/label_propagation.py
uttut/pipeline/bian/tests/test_label_propagation.py

Propagate labels according to given SpanGroup or EditGroup.

label propagate

---

uttut/pipeline/ops/merge_whitespace_characters.py
uttut/pipeline/ops/strip_whitespace_characters.py
uttut/pipeline/ops/tests/test_merge_whitespace_characters.py
uttut/pipeline/ops/tests/test_strip_whitespace_characters.py

1. MergeWhiteSpaceCharacters： \s+ -> ' '
2. StripWhiteSpaceCharacters: 去掉頭尾的空白字元

(Op) handle whitespace characters

---

uttut/pipeline/edit/lst2lst.py
uttut/pipeline/edit/replacement.py
uttut/pipeline/edit/tests/test_replacement.py
uttut/pipeline/edit/tests/test_replacement_group.py
uttut/pipeline/ops/add_sos_eos.py
uttut/pipeline/ops/pad.py
uttut/pipeline/ops/tests/test_add_sos_eos.py
uttut/pipeline/ops/tests/test_pad.py
uttut/pipeline/ops/tests/test_token_to_index.py
uttut/pipeline/ops/token_to_index.py
uttut/pipeline/ops/tokens.py

1. add_sos_eos: Insert `start token` to the head of input, then append `end token` at the end.
2. pad: Pad input sequence to a given length with `pad token`.
3. token2index: Assign token to an ordinal (integer)  based on given token2index mapping.

(Ops) List2List

---

uttut/pipeline/ops/add_sos_eos.py
uttut/pipeline/ops/base.py
uttut/pipeline/ops/pad.py
uttut/pipeline/ops/pattern_to_token.py
uttut/pipeline/ops/tests/test_add_sos_eos.py
uttut/pipeline/ops/tests/test_char_tokenizer.py
uttut/pipeline/ops/tests/test_eng_tokenizer.py
uttut/pipeline/ops/tests/test_float_token.py
uttut/pipeline/ops/tests/test_float_token_with_space.py
uttut/pipeline/ops/tests/test_int_token.py
uttut/pipeline/ops/tests/test_int_token_with_space.py
uttut/pipeline/ops/tests/test_merge_whitespace_characters.py
uttut/pipeline/ops/tests/test_pad.py
uttut/pipeline/ops/tests/test_strip_whitespace_characters.py
uttut/pipeline/ops/tests/test_token_to_index.py
uttut/pipeline/ops/tests/test_zh_char_tokenizer.py
uttut/pipeline/ops/token_to_index.py
uttut/pipeline/ops/tokenizer.py
uttut/pipeline/step.py
uttut/pipeline/tests/mock_factory.py
uttut/pipeline/tests/test_step.py

Main modification: Implement magic method `__eq__` for each operators.

Ops can compare with each other.

---

uttut/elements.c
uttut/elements.pyx
uttut/tests/test_elements.py

modified representation of elements

---

uttut/pipeline/edit/replacement.c
uttut/pipeline/edit/span.c
uttut/pipeline/edit/utils.c
uttut/pipeline/edit/validation.c

It seems that we should do `make clean` and `make clean-c` before `make installself` if the pyx file is altered.

just updated c files

---

setup.py

可以等 #90, #91 merge 完後 再 merge這個 
也可以不用等

version 1.3.0

---

setup.py

1.3.1 has a new operator: replace punctuation without endpoint with whitespace

version 1.3.1

---

setup.py

b0f2845 (HEAD -> version_133, tag: 1.3.3, origin/version_133) version 1.3.3
01d1797 (origin/master, origin/HEAD, master) property setter getter
467cd2e simplify
6b07cb8 use substring
53e3cfc TrieNode has more methods
09b7f3f added docstring
1b5135a added custom word tokenizer
59e9b58 added data structure: Trie
a5e7479 version 1.3.2

version 1.3.3

---

setup.py

Fix bug: Forget to register the latest op.

version 1.3.4

---

uttut/pipeline/ops/__init__.py
uttut/pipeline/ops/add_sos_eos.py
uttut/pipeline/ops/add_whitespace_around_character.py
uttut/pipeline/ops/base.py
uttut/pipeline/ops/lowercase.py
uttut/pipeline/ops/pad.py
uttut/pipeline/ops/pattern_recognizers/base.py
uttut/pipeline/ops/pattern_recognizers/float_token.py
uttut/pipeline/ops/pattern_recognizers/float_token_with_space.py
uttut/pipeline/ops/pattern_recognizers/int_token.py
uttut/pipeline/ops/pattern_recognizers/int_token_with_space.py
uttut/pipeline/ops/pattern_recognizers/merge_whitespace_characters.py
uttut/pipeline/ops/pattern_recognizers/strip_whitespace_characters.py
uttut/pipeline/ops/punctuation_except_endpoint_to_whitespace.py
uttut/pipeline/ops/span_subwords.py
uttut/pipeline/ops/strip_accent_token.py
uttut/pipeline/ops/token_to_index.py
uttut/pipeline/ops/token_to_index_with_hash.py
uttut/pipeline/ops/tokenizers/base.py
uttut/pipeline/ops/tokenizers/char_tokenizer.py
uttut/pipeline/ops/tokenizers/custom_word_tokenizer.py
uttut/pipeline/ops/tokenizers/eng_tokenizer.py
uttut/pipeline/ops/tokenizers/whitespace_tokenizer.py
uttut/pipeline/tests/mock_factory.py
uttut/pipeline/tests/test_step.py

把該是 class attribute 的東西從 `__init__` 拿掉
並用 `__init_subclass__` 來檢查 class attribute 有被定義

Refactor operation base

---

uttut/pipeline/ops/base.py
uttut/pipeline/ops/pattern_recognizers/base.py
uttut/pipeline/ops/tests/common_tests.py
uttut/pipeline/ops/tokenizers/base.py
uttut/pipeline/pipe.py
uttut/pipeline/tests/test_pipe.py

參考 keras model.summary
範例：
```
________________________________________________________________________________
Type  Operator
================================================================================
str
v
|    MergeWhiteSpaceCharacters()
|    StripWhiteSpaceCharacters()
|    CharTokenizer()
v
list
v
|    AddSosEos(start_token='<sos>', end_token='</s>')
|
@--> checkpoint: 'result_of_add_sos_eos'
|
|    Pad(maxlen=50, pad_token='<pad>')
|
@--> checkpoint: 'result_of_pad'
|
|    Token2Index(token2index={'<sos>': 0, '</s>': 1, ...}, unk_token='<unk>')
v
================================================================================
str -> list
Total operators: 6
Total checkpoints: 2
________________________________________________________________________________
```
空的話則會：
``` …
```

Pipe summary

---

uttut/pipeline/ops/base.py
uttut/pipeline/ops/tests/common_tests.py
uttut/pipeline/pipe.py

use f"{!r}" replace inline repr

---

uttut/pipeline/pipe.py
uttut/pipeline/tests/mock_factory.py
uttut/pipeline/tests/test_pipe.py

Pipe utility

---

setup.py

Modifications:
- uninstall pypandoc, use content_type instead
- human readable dump

release-1.4.5

---

uttut/__version__.py

Main modifications from 1.4.5 - 1.4.6:
- 991ef5d Merge pull request #128 from Yoctol/version_file
- 7f6973d Merge pull request #126 from Yoctol/num_token
- d8d6412 Merge pull request #127 from Yoctol/bert-pipe-readme
- 8c98095 Merge pull request #125 from Yoctol/consider_fullwidth_number
- 0bc0d9c Merge pull request #123 from Yoctol/removed_stopwords
- b4d081e Merge pull request #124 from Yoctol/modified_makefile

version 1.4.6

---

setup.py
uttut/__version__.py

ref: https://python-packaging.readthedocs.io/en/latest/non-code-files.html

include package data = True

---

uttut/__version__.py

version 1.4.9

---

uttut/pipeline/ops/__init__.py
uttut/pipeline/ops/pattern_recognizers/__init__.py
uttut/pipeline/ops/pattern_recognizers/replace_a_with_b.py
uttut/pipeline/ops/pattern_recognizers/tests/test_replace_a_with_b.py

Recognize a (pattern or substring)  in the input string and replace them with b.
```python
>>> from uttut.pipeline.ops.pattern_recognizers.replace_a_with_b import
ReplaceAwithB
>>> op = ReplaceAwithB(a=r'[\.]+', b="X")
>>> output_seq, label_aligner = op.transform("10....7")
>>> output_labels = label_aligner.transform([1, 1, 1, 2, 1, 1, 1])
>>> output_seq
"10X7"
>>> output_labels
[1, 1, 1, 1]
>>> label_aligner.inverse_transform(output_labels)
[1, 1, 1, 1, 1, 1, 1]
```

added operation replace a with b

---

uttut/__version__.py

Main Modifications:
fa84764 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #135 from Yoctol/replace_a_with_b
4f94cde Merge pull request #134 from Yoctol/added_whitespace_around_words
7cbf5fa (origin/added_whitespace_around_words, added_whitespace_around_words) added testcase: invalid op
15225cc (origin/replace_a_with_b, replace_a_with_b) added operation replace a with b
0f832b1 added docstring
07b7b0d added operation: add whitespace around word and zhchar

version 1.4.10
